---
# Vagrant hostname and IP configuration.
vagrant_hostname: local.wet4.dev
vagrant_ip: 10.10.10.10
vagrant_user: vagrant
vagrant_home: /home/vagrant
vagrant_webroot: /var/www/drupal

# Synced Folders
vagrant_synced_folders:
  - local_path: ~/Sites/wet4
    destination: /var/www
    id: drupal
    type: nfs
    create: true

# Memory and CPU to use for this VM.
vagrant_memory: 4096
vagrant_cpus: 2

ansible_os_family: Debian
#ansible_os_family: RedHat

build_environment: development
# build_environment: production

# Server Extras
installed_extras:
  - mailhogx
  - memcached
  - phpmyadmin
  - pimpmylog
  # - solr
  # - selenium
  - xdebug
  - xhprof
  # - nodejs
  # - varnish
  - checkpoint