---
- name: Do not accept locale environment variables passed over SSH.
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^AcceptEnv LANG"
    state: absent
    validate: "/usr/sbin/sshd -T -f %s"

# Originally I tried adding to the www group, but because Ansible uses one SSH
# connection, that broke the initial provisioning, since groups aren't refreshed
# without a new session or log off/log on.
- name: Ensure necessary groups exist.
  group: "name={{ item }} state=present"
  with_items:
    - admin
    - dialout

- name: Ensure vagrant user is in admin group.
  user: "name={{ vagrant_user }} append=yes groups=admin"

- name: Ensure www-data user is in dialout group (Debian).
  user: "name=www-data append=yes groups=dialout"
  when: ansible_os_family == 'Debian'

- name: Set nicer permissions on Apache log directory.
  file:
    path: "/var/log/{{ apache_daemon }}"
    state: directory
    mode: 0755
    recurse: true

# Fix: http://code.girishrao.me/tag/mysql/ 
- name: Ensure MySQL AppArmor profile is disabled (for slow query log).
  file:
    path: /etc/apparmor.d/disable/usr.sbin.mysqld
    src: /etc/apparmor.d/usr.sbin.mysqld
    state: link
  register: mysql_apparmor
  when: mysql_slow_query_log_enabled

- name: Restart AppArmor if necessary.
  service: name=apparmor state=restarted
  when: mysql_apparmor.changed