---
# Drupal

# Download Drupal using Git.
- name: Check out Drupal Core to the default location.
  git: >
    repo={{ drupal_repo_url }}
    version={{ drupal_core_version }}
    update={{ drupal_keep_updated }}
    depth=1
    dest={{ drupal_core_path }}

# Download Checkpoint using Git.
- name: Check out Checkpoint profile
  git: >
    repo={{ checkpoint_repo_url }}
    version={{ checkpoint_version }}
    update={{ checkpoint_keep_updated }}
    depth=1
    dest={{ drupal_core_path }}/profiles/checkpoint/

# Intall Drupal
- name: Install Drupal.
  command: >
    drush si {{ drupal_install_profile }} -y
    --site-name="{{ drupal_site_name }}"
    --account-name={{ drupal_admin_name }}
    --account-pass={{ drupal_admin_password}}
    --db-url=mysql://{{ drupal_mysql_user }}:{{ drupal_mysql_password }}@localhost/{{ drupal_mysql_database }}
    chdir={{ drupal_core_path }}
    creates={{ drupal_core_path }}/sites/default/settings.php

# SEE: https://drupal.org/node/2121849#comment-8413637
- name: Set permissions properly on settings.php.
  file: >
    path={{ drupal_core_path }}/sites/default/settings.php
    mode=744

- name: Set permissions properly on files directory.
  file: >
    path={{ drupal_core_path }}/sites/default/files
    mode=777
    state=directory
    recurse=yes

# Disable the overlay and toolbar modules
- name: Disable the overlay and toolbar modules
  command: >
    drush dis -y overlay, toolbar
    chdir={{ drupal_core_path }}  
  ignore_errors: yes